name: 배포해줘잉

# This workflow is triggered on merges to the main branch
on:
  push:
    branches:
      - main

jobs:
  trigger-jenkins-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Trigger Jenkins Job
      uses: appleboy/jenkins-action@master
      with:
        url: ${{ secrets.WEBHOOK_URL }}
        user: ${{ github.actor }}
        token: ${{ secrets.JENKINS_API_TOKEN }}
        job: "BloGeeK-Data"

    - name: Check Job Status
      run: |
        JENKINS_JOB_URL="${{ steps.trigger-job.outputs.job_url }}"
        # Poll the Jenkins job status
        # (You need to write a script here to poll the status of the Jenkins job)
        # If the job fails, exit with a non-zero status to fail the workflow
