name: 배포해줘잉

# This workflow is triggered on merges to the main branch
on:
  pull_request:
      branches: [ main ]

jobs:
  trigger-jenkins-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Trigger Jenkins Job
      uses: appleboy/jenkins-action@master
      with:
        url: ${{ secrets.WEBHOOK_URL }}
        user: ${{ github.actor }}
        token: ${{ secrets.JENKINS_API_TOKEN }}
        job: "BloGeeK-Data"

    - name: Wait for Jenkins Job to Complete
      id: wait-for-job
      env:
        JENKINS_JOB_URL: ${{ secrets.JENKINS_JOB_STATUS_URL }} # Set your Jenkins job status URL in secrets
        JENKINS_USER: ${{ github.actor }}
        JENKINS_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
        
      run: |
        STATUS=""
        JOB_URL="$JENKINS_JOB_URL"
        
        while [ "$STATUS" != "SUCCESS" ]; do
          RESPONSE=$(curl -s -u $JENKINS_USER:$JENKINS_TOKEN "$JOB_URL")
          STATUS=$(echo $RESPONSE | jq -r '.result') # Parsing JSON response to get the job result

          if [ "$STATUS" == "FAILURE" ]; then
            echo "Jenkins job failed"
            exit 1
          elif [ "$STATUS" == "SUCCESS" ]; then
            echo "Jenkins job succeeded"
            break
          else
            echo "Waiting for job to complete..."
            sleep 30 # Wait for 30 seconds before the next poll
          fi
        done
