name: Jenkins Job Trigger

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '.github/workflows/**'

jobs:

  commit_to_main :
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Work Test
        run: |
          echo "A"
      #- name: Trigger Jenkins Job for main branch
      #  uses: appleboy/jenkins-action@master
      #  with:
      #    url: ${{ secrets.JENKINS_URL }} # Your Jenkins URL
      #    user: ${{ secrets.JENKINS_USER }} # Your Jenkins username
      #    token: ${{ secrets.JENKINS_TOKEN }} # Your Jenkins token
      #    job: 'commit_to_main' # Jenkins job name

  python_convention:
    runs-on: ubuntu-latest
    steps:
      - name: Work Test
        run: |
          echo "B"
      #- name: Trigger Jenkins Job for Python convention
      #  uses: appleboy/jenkins-action@master
      #  with:
      #    url: ${{ secrets.JENKINS_URL }} # Your Jenkins URL
      #    user: ${{ secrets.JENKINS_USER }} # Your Jenkins username
      #    token: ${{ secrets.JENKINS_TOKEN }} # Your Jenkins token
      #    job: 'python_convention' # Jenkins job name
